# config.yaml

# ğŸ•°ï¸ PerÃ­odos grÃ¡ficos utilizados no backtest
timeframes:
  - 15m

# ğŸ“… Intervalo de anos para o backtest
start_year: 2018
end_year: 2025

# ğŸ” Lookback usado para cÃ¡lculo de mÃ­nimas/mÃ¡ximas
lookback: 200

# ğŸ”¢ Quantidade de candles por backtest
candle_limit: 1000

# ğŸª™ Lista de criptomoedas a testar
cryptos:
  - BTCUSDT

# ğŸ¦ Nome da exchange a ser utilizada
exchange_name: binance

# ğŸ“ Pasta onde serÃ£o salvos os arquivos de resultado
output_folder: backtest
